export const FETCH_CARDS = 'FETCH_CARDS';
export const FETCH_CARDS_PENDING = 'FETCH_CARDS_PENDING';
export const FETCH_CARDS_FULFILLED = 'FETCH_CARDS_FULFILLED';
export const FETCH_CARDS_REJECTED = 'FETCH_CARDS_REJECTED';

export const SHUFFLE_CARDS = 'SHUFFLE_CARDS';
export const SHUFFLE_CARDS_PENDING = 'SHUFFLE_CARDS_PENDING';
export const SHUFFLE_CARDS_FULFILLED = 'SHUFFLE_CARDS_FULFILLED';
export const SHUFFLE_CARDS_REJECTED = 'SHUFFLE_CARDS_REJECTED';

export const DEAL_ONE_CARD = 'DEAL_ONE_CARD';
export const DEAL_ONE_CARD_PENDING = 'DEAL_ONE_CARD_PENDING';
export const DEAL_ONE_CARD_FULFILLED = 'DEAL_ONE_CARD_FULFILLED';
export const DEAL_ONE_CARD_REJECTED = 'DEAL_ONE_CARD_REJECTED';
